[package]
name = "lambda_stlc_module"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15.1"
axum = "0.7"
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
